// Generate random history data
const generateHistory = (baseline, variance = 0.1, count = 12) => {
  return Array(count)
    .fill(0)
    .map((_, i) => {
      const date = new Date();
      date.setMonth(date.getMonth() - (count - i - 1));
      const value = baseline * (1 + (Math.random() * 2 - 1) * variance);
      return {
        date: date.toISOString().split("T")[0],
        value: Number(value.toFixed(2)),
      };
    });
};

export const kpis = {
  "public-works": [
    {
      id: "pw-1",
      name: "Average project delay",
      value: 12.3,
      target: 9,
      unit: "days",
      trend: "down",
      isGoodTrend: true,
      history: generateHistory(15, 0.2),
    },
    {
      id: "pw-2",
      name: "Milestones met on time",
      value: 78,
      target: 90,
      unit: "%",
      trend: "up",
      isGoodTrend: true,
      history: generateHistory(70, 0.15),
    },
    {
      id: "pw-3",
      name: "Contractor response time",
      value: 8.5,
      target: 6,
      unit: "hours",
      trend: "down",
      isGoodTrend: true,
      history: generateHistory(10, 0.25),
    },
    {
      id: "pw-4",
      name: "High-risk defects identified",
      value: 24,
      target: 30,
      unit: "count",
      trend: "up",
      isGoodTrend: true,
      history: generateHistory(20, 0.3),
    },
  ],
  customs: [
    {
      id: "cu-1",
      name: "Average clearance time",
      value: 52,
      target: 45,
      unit: "min",
      trend: "down",
      isGoodTrend: true,
      history: generateHistory(60, 0.2),
    },
    {
      id: "cu-2",
      name: "Shipments cleared within SLA",
      value: 85,
      target: 95,
      unit: "%",
      trend: "up",
      isGoodTrend: true,
      history: generateHistory(80, 0.1),
    },
    {
      id: "cu-3",
      name: "False-positive rate",
      value: 15,
      target: 10,
      unit: "%",
      trend: "down",
      isGoodTrend: true,
      history: generateHistory(18, 0.25),
    },
    {
      id: "cu-4",
      name: "Prediction accuracy",
      value: 82,
      target: 88,
      unit: "%",
      trend: "up",
      isGoodTrend: true,
      history: generateHistory(78, 0.08),
    },
  ],
  "economic-development": [
    {
      id: "ed-1",
      name: "Average license issuance time",
      value: 2.8,
      target: 2,
      unit: "days",
      trend: "down",
      isGoodTrend: true,
      history: generateHistory(3.5, 0.15),
    },
    {
      id: "ed-2",
      name: "License renewal rate",
      value: 76,
      target: 85,
      unit: "%",
      trend: "up",
      isGoodTrend: true,
      history: generateHistory(70, 0.12),
    },
    {
      id: "ed-3",
      name: "Customer satisfaction (NPS)",
      value: 35,
      target: 40,
      unit: "score",
      trend: "up",
      isGoodTrend: true,
      history: generateHistory(30, 0.2),
    },
    {
      id: "ed-4",
      name: "SME GDP contribution",
      value: 28,
      target: 30,
      unit: "%",
      trend: "up",
      isGoodTrend: true,
      history: generateHistory(26, 0.05),
    },
  ],
  "public-services": [
    {
      id: "ps-1",
      name: "Average resolution time",
      value: 58,
      target: 48,
      unit: "hours",
      trend: "down",
      isGoodTrend: true,
      history: generateHistory(65, 0.2),
    },
    {
      id: "ps-2",
      name: "First-response rate",
      value: 82,
      target: 90,
      unit: "%",
      trend: "up",
      isGoodTrend: true,
      history: generateHistory(75, 0.1),
    },
    {
      id: "ps-3",
      name: "Citizen satisfaction score",
      value: 4.1,
      target: 4.5,
      unit: "/5",
      trend: "up",
      isGoodTrend: true,
      history: generateHistory(3.8, 0.1),
    },
    {
      id: "ps-4",
      name: "Services available online",
      value: 63,
      target: 75,
      unit: "%",
      trend: "up",
      isGoodTrend: true,
      history: generateHistory(55, 0.15),
    },
  ],
  transport: [
    {
      id: "tr-1",
      name: "Average passenger wait time",
      value: 8.4,
      target: 6,
      unit: "min",
      trend: "down",
      isGoodTrend: true,
      history: generateHistory(10, 0.25),
    },
    {
      id: "tr-2",
      name: "On-time performance",
      value: 88,
      target: 95,
      unit: "%",
      trend: "up",
      isGoodTrend: true,
      history: generateHistory(85, 0.1),
    },
    {
      id: "tr-3",
      name: "Vehicle load factor",
      value: 64,
      target: 70,
      unit: "%",
      trend: "up",
      isGoodTrend: true,
      history: generateHistory(60, 0.15),
    },
    {
      id: "tr-4",
      name: "Vehicle idle rate",
      value: 14,
      target: 10,
      unit: "%",
      trend: "down",
      isGoodTrend: true,
      history: generateHistory(18, 0.2),
    },
  ],
};
